name: JenkinsDocker
services:
  jenkins:
    build:
      context: ./
    privileged: true
    user: root
    ports:
      - 8383:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/arman/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
